openapi: 3.0.0
info:
  title: Twitter API Documentation
  version: 1.0.0
paths:
  /2/tweets/search/recent:
    get:
      summary: Search recent tweets.
      parameters:
        - name: query
          in: query
          required: true
          description: Search query.
          schema:
            type: string
        - name: max_results
          in: query
          required: false
          description: Max number of results.
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Successful response.
